#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s ${SCRIPTPATH}/down /tmp/leftwm-theme-down

#boot compton or picom if it exists
if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null & 
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null & 
fi

#set the theme.toml config
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill "${SCRIPTPATH}/background.jpg"
fi

# extra utils to make this theme a little more homey
if [ -x "$(command -v dunst)" ]; then
  dunst -conf "${SCRIPTPATH}/dunst/config" &
fi

#boot a polybar for each monitor
cd ${SCRIPTPATH}/polybar
polybar -m | sed s/:.*// | tac | while read -r monitor
do 
  monitor=$monitor polybar -c config.ini main &> /dev/null &
done

if [ -x "$(command -v xss-lock)" ]; then
  xss-lock i3lock-fancy-rapid 5 pixel &
fi
